'use strict';

//   Create a module to house all of routes for the authentication system.
const express = require('express');
const router = express.Router();
const basicAuth = require('./middleware/basic');
const User = require('./models/users-model');

router.post('/signup', async (req, res, next) => {
  // Create a POST route for /signup
  // Accepts either a JSON object or FORM Data with the keys “username” and “password”
  // Creates a new user record in a Mongo database
  let newUser = await new User(req.body);
  newUser.save().then(newUser => {
    res.status(200).json(newUser);
  });
});

// Create a POST route for /signin
// router.post('/signin', basicAuth, (req,res) => {});
// Uses middleware (BasicAuthentication) to validate the user
router.post('/signin', basicAuth, (req, res, next) => {
  // When validated, send a JSON object as the response with the following properties:
  // token: The token generated by the users model
  // user: The users’ database record
  res.status(200).json({ token: req.token, user: req.user });
  // Additionally, set a Cookie and a Token header on the response, with the token as the value
  res.cookie('basicAuth', req.token);
});

router.get('/users', async (req, res, next) => {
  // Create a GET route for /users that returns a JSON object with all users
  let recordsToGet = await User.findAll();
  res.status(200).json(recordsToGet);
});

module.exports = router;
