'use strict';

//   Create a module to house all of routes for the authentication system.
const express = require('express');
const router = express.Router();
const basicAuth = require('./middleware/basic');

router.post('/signup', (req, res, next) => {
  // Create a POST route for /signup
  // Accepts either a JSON object or FORM Data with the keys “username” and “password”
  // Creates a new user record in a Mongo database
});

router.post('/signin', basicAuth, (req, res, next) => {
  // Create a POST route for /signin
  // router.post('/signin', basicAuth, (req,res) => {});
  // Uses middleware (BasicAuthentication) to validate the user
  // When validated, send a JSON object as the response with the following properties:
  // token: The token generated by the users model
  // user: The users’ database record
  // Additionally, set a Cookie and a Token header on the response, with the token as the value
});

router.get('/users', (req, res, next) => {
  // Create a GET route for /users that returns a JSON object with all users
});

module.exports = router;
